apiVersion: aws.hops.ops.com.ai/v1alpha1
kind: RegistryCache
metadata:
  name: platform-registry-cache
  namespace: default
spec:
  accountId: "123456789012"
  region: us-east-2
  distribution:
    enabled: true
    podIdentity:
      enabled: false
    upstreams:
      - name: xpkg-crossplane
        sourceRegistry: xpkg.crossplane.io
